### ISSUE TITLE
Automatically prevent double navigation actions somehow

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/rfcs#16] opened 2018-02-09 17:45 UTC
You can do this manually with idempotent pushes now: https://github.com/react-navigation/react-navigation.github.io/issues/42
But it would be nice if we can somehow handle this automatically (without resorting to some kind of debouncing of the actions): https://github.com/react-navigation/react-navigation/pull/1348

**Comment by dantman** [comment] 2018-02-10 05:28
I'm of two opinions.

Firstly, I don't think react-navigation should be responsible for preventing this on its own. It's an interesting extra feature, but I don't think react-navigation handling this should be the gold standard.
If you double submit an ajax call you get 2 HTTP requests, if you double submit a "ADD_ITEM" redux dispatch you add two items, if you double submit a form you get 2 HTTP POSTs, if you double submit an `INSERT` row for a sqlite database you get 2 new rows.
There are dozens of things other than a `navigate` dispatch you can do as part of a button press or other double submittable user action. And just about all of them will have similar issues of an unwanted extra being created.
As such I think the gold standard here is providing a way to make preventing double submit for any user action event easy. My preference would be creating a recommended library for this functionality (ie: blocking subsequent calls to a handler until the task started by the first one finishes). And providing an easy to use signal in react-navigation to indicate when a navigate action's task completes (ie: when all queued navigate actions have finished their transitions). Like a `TransitionManager.isTransitioning() => bool`, `TransitionManager.runAfterTransition(cb)`, and/or `TransitionManager.waitForTransitions() => Promise`

Secondly however, if you do want to handle this automatically as an extra feature I have already come up with a fairly unobtrusive way of making navigate actions idempotent automatically.
It was in the second half of this comment: https://github.com/react-navigation/react-navigation/pull/2578#issuecomment-330835051
The basic idea is making `navigate` work like `goBack` where the key of the **source** (the route the action is being dispatched from, not the key of the route being created) is included and giving `navigate` a "exclusive push after" semantics (ie: fail with a warning if a route already exists after this route).

**Comment by satya164** [comment] 2018-02-10 12:36
> Firstly, I don't think react-navigation should be responsible for preventing this on its own.

Native handles this automatically, and it's a common enough issue that react navigation should handle automatically IMO. I think it's unreasonable to manually handle it for every button in the app even if it was easy.

From my reply in the discussion on slack earlier:

I think we need several heuristics to block duplicate navigation actions:
1. Both navigation actions should originate from the same screen (same key)
2. Both navigation actions should be of the same type, e.g.  both should be `PUSH`
3. Both navigation actions should happen in short-interval, e.g. between the start and end of transition 

Otherwise, it might block intentional navigations, e.g. user clicked another button or press back before the transition actually finished, or there is a `RESET` action after `PUSH`

**Comment by Vishal1419** [comment] 2018-02-16 08:28
When are you planning to release a new version which will have the capability to accept key in navigation function?

**Comment by brentvatne** [comment] 2018-02-18 20:56
@Vishal1419 - `this.props.navigation.navigate({routeName: 'abc', key: 'whatever'})`

**Comment by evanjmg** [comment] 2018-02-27 21:04
key works for most cases, but if you navigate from the side drawer and then open the sidedrawer again and navigate to the same key  it breaks :(.  These bugs need to be fixed, but yeah let's keep the key solution!
```
debounce(() => {
    this.props.navigation.navigate(PAYMENT_DETAILS_VIEW)
  }, 750, { leading: true,  trailing: false })

**Comment by brentvatne** [comment] 2018-02-28 06:17
@evanjmg - can you post a demo of this on https://snack.expo.io? happy to investigate that

**Comment by brentvatne** [comment] 2018-03-02 21:17
will need you to post a repro case to https://snack.expo.io @radiodario. this works as expected for me: https://snack.expo.io/SyeO1SwOG

**Comment by evanjmg** [comment] 2018-03-02 22:00
I have an example here when I go to B, I can't go back to new A? Shouldn't it go back to it without using goBack? https://snack.expo.io/@evanjmg/idempotent-navigate  . Unfortunately I cannot reproduce my sidebar bug, but nested navigators I think need more work.

**Comment by brentvatne** [comment] 2018-03-03 00:09
@evanjmg - I re-organized that example to be a bit more clear: https://snack.expo.io/SJxu8wv_f

you can't navigate to A with the key `UNIQKEY!` because there is no route A with key `UNIQKEY!`. the difficulty here is that you can't specify the key for the initial route and it's dynamically generated. so if you want to navigate back to it, you need to use `goBack()`. there are two upcoming changes that make it so you can easily use `navigate` for this:

- https://github.com/react-navigation/react-navigation/pull/3540
- https://github.com/react-navigation/rfcs/pull/25

> but I think nested navigators need more work.

what do you mean? it's not possible to act on feedback like this, we need more specific information ;)

> Also, open the sidebar and click the one of buttons really fast. They will eventually stop working on slow taps, it's not an issue for without key.

can't repro this, can you post a video? what does stop working mean?

**Comment by evanjmg** [comment] 2018-03-03 00:13
Some improvements:
- the drawer stack navigator should have an option to enable headers. 
- routing from parent navigator to sub navigators without using initial route name and rather just using a key to reference the child navigator

**Comment by brentvatne** [comment] 2018-03-03 00:16
> the drawer stack navigator should have an option to enable headers.

just put a stack inside or put a drawer inside a stack

> routing from parent navigator to sub navigators without using initial route name and rather just using a key to reference the child navigator

see the rfc i mentioned

**Comment by armanbabai** [comment] 2018-03-09 22:00
oh. not work on my device huawei y221 !

**Comment by rbadr** [comment] 2018-03-27 13:43
I completely agree with @satya164 , it's really a big issue for a lot of users and especially in production apps (users have different mobile phones, old/laggy ...), and react-navigation should be able to handle it (checking the route name and params before pushing a new route). 

@brentvatne  I have tried idempotent pushes but in dev mode it display the red screen (should not push route with duplicated key) when you push a route with the same key, and sometimes it mounts the same screen and unmout it quickly. 
It also doesn't work with NavigationActions.navigate unfortunately.

We're using now debouncing on every button in our app to avoid duplicating screens (which is just a hack). 

I hope that we can find a solution for this issue, and would love to help if necessary !

**Comment by jeevantakhar** [comment] 2018-03-27 18:37
@rbadr Are you able to use unique keys?

**Comment by rbadr** [comment] 2018-03-29 08:29
@jeevantakhar I'm generating my own custom unique key

**Comment by nisargap** [comment] 2018-04-02 16:48
Using debounce with a 0 timeout (i.e. happens immediately) along with passing a unique key on the dispatch also solved it for me.

 #[271] @nihgwu's reducer modification response also helped solve the issue.

**Comment by Chooster** [comment] 2018-05-02 20:11
I'm getting the same error as @radiodario.
Here is my StackNavigator which is nested inside of a TabNavigator:
```
import React from 'react';
import { TouchableOpacity, View, Text, Button } from 'react-native';
import { StackNavigator } from 'react-navigation';
import { Icon } from 'native-base';

import Profile from './Profile';
import Settings from './Settings';

import NavBar from '../../Components/NavBar';

import Colors from '../../../constants/Colors';

export default StackNavigator(
  {
    Profile: {
      screen: Profile,
      navigationOptions: ({ navigation }) => ({
        headerRight: (
          <TouchableOpacity
            onPress={() =>
              navigation.navigate({
                routeName: 'Settings',
                key: 'SettingsScreen'
              })
            }
          >
            <Icon name="ios-settings" style={{ paddingRight: 10 }} />
          </TouchableOpacity>
        ),
        headerTitle: navigation.state.routeName
      })
    },
    Settings: {
      screen: Settings,
      navigationOptions: ({ navigation }) => ({
        headerLeft: (
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Icon name="ios-arrow-back" style={{ paddingLeft: 10 }} />
          </TouchableOpacity>
        ),
        headerTitle: navigation.state.routeName
      })
    }
  },
  {
    navigationOptions: ({ navigation }) => ({
      // header: props => <NavBar {...props} {...navigation} />
      headerStyle: {
        backgroundColor: Colors.tintColor,
        shadowOffset: { width: 0, height: 0 },
        shadowRadius: 3,
        shadowOpacity: 0.3
      },
      headerTitle: props => <Text style={props.style}>{props.children}</Text>,
      headerTitleStyle: {
        flex: 1,
        fontFamily: 'bold',
        textAlign: 'center',
        letterSpacing: -0.2
      },
      headerLeft: <View />, // Empty View's to Center Title on Android
      headerRight: <View />
    })
  }
);
```
Error: `should not push route with duplicated key SettingsScreen`

**Comment by jeffreymendez1993** [comment] 2018-05-04 11:41
This issue occurs if you rapidly press on something to navigate it will try to push a duplicate scene. To solve this keep track of the scene once you call navigate and make sure its not === to the same route onPress.

**Comment by Rutulpatel7077** [comment] 2018-06-18 18:00
+1

**Comment by ericvicenti** [comment] 2018-06-18 18:12
This issue is fixed in recent versions of `react-navigation`. Just provide a unique key when you call `navigation.navigate({ routeName: 'RouteName', key: 'unique-route' })`

**Closed by ericvicenti** 2018-06-18 18:12 UTC

**Comment by Rutulpatel7077** [comment] 2018-06-18 18:15
I am using `"react-navigation": "1.3.1",` which version you are talking about ? @evanjmg

**Comment by Rutulpatel7077** [comment] 2018-06-18 18:47
Thanks! It works!

**Comment by MacKentoch** [comment] 2018-06-29 09:39
Still not fixed in V2 it can navigate twice to same scene even if using a unique key to navigate().

**Comment by brentvatne** [comment] 2018-06-29 14:22
@MacKentoch - post an issue with a repro
