### ISSUE TITLE
Event emitter for header button

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/rfcs#48] opened 2018-06-11 17:39 UTC
Works fine in react-native-navigation, we did the same thing in ex-navigation and it was ok too. It certainly doesn't feel ideal but it's better than params.

More in https://github.com/react-navigation/react-navigation/issues/145#issuecomment-396311054

**Comment by brentvatne** [comment] 2018-06-11 17:43
fwiw I'm not totally convinced this is needed, we should definitely update the docs to explain the concern that the user had in the comment I linked to above, though. also we should add `getParam`

**Comment by satya164** [comment] 2019-09-20 00:17
Duplicate of #20

**Closed by satya164** 2019-09-20 00:17 UTC
